language: python
before_install:
- pip install pyinstaller
- pip install pycodestyle
script:
- pycodestyle svtgui.py
- pytest
- pyinstaller --onefile --windowed --add-binary $(which svtplay-dl):. svtgui.py
deploy:
  edge: true
  provider: releases
  file: dist/svtgui
  draft: true
